const FIVE_MINUTES = 300
const FIFTEEN_MINUTES = 900
const THIRTY_MINUTES = 900
const SIXTY_MINUTES = 3600

module.exports = {
    FIVE_MINUTES,
    FIFTEEN_MINUTES,
    THIRTY_MINUTES,
    SIXTY_MINUTES
}